#!/usr/bin/env bash
# a Bash script that configures an Ubuntu serve.
# Requirements:
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8.
# The checker is running on Docker, so make sure to read this
ifconfig 127.0.0.2 8.8.8.8
